// Reads src/data/learningArticles.ts and emits a Python seed function
// (_reseed_articles_v2) that stores each article as markdown body plus
// key_takeaways and references, preserving the copy verbatim.
import { readFileSync, writeFileSync } from 'fs'

const src = readFileSync('src/data/learningArticles.ts', 'utf8')
const marker = 'export const learningCategories: LearningCategory[] = '
const start = src.indexOf(marker)
if (start === -1) throw new Error('learningCategories not found')
let arrText = src.slice(start + marker.length).trim()
if (arrText.endsWith(';')) arrText = arrText.slice(0, -1)
const categories = JSON.parse(arrText)

function blocksToMarkdown(body) {
  const parts = []
  for (const b of body) {
    if (b.type === 'h3') parts.push(`## ${b.text}`)
    else if (b.type === 'ul') parts.push((b.items || []).map((i) => `- ${i}`).join('\n'))
    else parts.push(b.text || '')
  }
  return parts.join('\n\n')
}

const rows = []
let sort = 1
for (const cat of categories) {
  for (const a of cat.articles) {
    rows.push({
      title: a.title,
      content: blocksToMarkdown(a.body),
      summary: a.dek,
      category: cat.name,
      age_group: a.ageTag,
      author: a.author,
      key_takeaways: (a.keyTakeaways || []).join('\n'),
      further_reading: (a.references || []).join('\n'),
      sort_order: sort++,
      active: 1,
    })
  }
}

function pyStr(s) {
  // Emit a Python single-quoted string literal with escapes.
  return "'" + String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n').replace(/\r/g, '') + "'"
}

let out = ''
out += '# AUTO-GENERATED by scripts/gen_article_seed.mjs from src/data/learningArticles.ts\n'
out += '# Do not edit by hand. Article copy is verbatim from the master content.\n\n'
out += 'ARTICLES_V2 = [\n'
for (const r of rows) {
  out += '    {\n'
  out += `        "title": ${pyStr(r.title)},\n`
  out += `        "content": ${pyStr(r.content)},\n`
  out += `        "summary": ${pyStr(r.summary)},\n`
  out += `        "category": ${pyStr(r.category)},\n`
  out += `        "age_group": ${pyStr(r.age_group)},\n`
  out += `        "author": ${pyStr(r.author)},\n`
  out += `        "key_takeaways": ${pyStr(r.key_takeaways)},\n`
  out += `        "further_reading": ${pyStr(r.further_reading)},\n`
  out += `        "sort_order": ${r.sort_order},\n`
  out += `        "active": 1,\n`
  out += '    },\n'
}
out += ']\n'

writeFileSync('backend/app/article_seed_data.py', out)
console.log(`Wrote ${rows.length} articles to backend/app/article_seed_data.py`)
